name: Build DEB Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper fakeroot


      - name: Build DEB Package
        run: |
          mkdir -p build
          cp -r . build/
          cd build
          debuild -us -uc || { echo "DEB package build failed"; exit 1; }


      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hardn-deb-package
          path: build/*.deb