#!/bin/bash
set -e

is_installed() {
    if command -v apt >/dev/null 2>&1; then
        dpkg -s "$1" >/dev/null 2>&1
    elif command -v dnf >/dev/null 2>&1; then
        dnf list installed "$1" >/dev/null 2>&1
    elif command -v yum >/dev/null 2>&1; then
        yum list installed "$1" >/dev/null 2>&1
    elif command -v rpm >/dev/null 2>&1; then
        rpm -q "$1" >/dev/null 2>&1
    else
        return 1 # Cannot determine package manager
    fi
}

if ! is_installed auditd; then
    HARDN_STATUS "info" "Installing auditd..."
    if command -v apt >/dev/null 2>&1; then
        apt install -y auditd >/dev/null 2>&1
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y auditd >/dev/null 2>&1
    elif command -v yum >/dev/null 2>&1; then
        yum install -y auditd >/dev/null 2>&1
    fi
fi

systemctl daemon-reload
systemctl enable auditd
systemctl restart auditd

HARDN_STATUS "info" "Configuring auditd rules for system security..."

audit_rules_file="/etc/audit/rules.d/hardn-xdr.rules"
cat > "$audit_rules_file" << 'EOF'
# This file is automatically generated by HARDN-XDR for STIG compliance.
# MITRE ATT&CK mappings included for key rules.
#
# Remove any existing rules
-D

# Increase the buffers to absorb a larger burst of events
-b 8192

# Set failure mode to syslog
-f 1

# Audit system startup and shutdown
# ATT&CK: T1529 (System Shutdown/Reboot)
-w /sbin/init -p x -k system-lifecycle
-w /sbin/reboot -p x -k system-lifecycle
-w /sbin/halt -p x -k system-lifecycle
-w /sbin/poweroff -p x -k system-lifecycle
-w /usr/sbin/shutdown -p x -k system-lifecycle

# Audit account, group, and authentication database changes
# ATT&CK: T1098 (Account Manipulation)
-w /etc/passwd -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-info
-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-info

# Audit changes to system configuration files
# ATT&CK: T1562 (Impair Defenses), T1112 (Modify Registry/Config)
-w /etc/sysconfig/ -p wa -k system-config
-w /etc/default/ -p wa -k system-config
-w /etc/security/ -p wa -k system-config
-w /etc/pam.d/ -p wa -k system-config
-w /etc/login.defs -p wa -k system-config
-w /etc/bashrc -p wa -k system-config
-w /etc/profile -p wa -k system-config
-w /etc/csh.cshrc -p wa -k system-config
-w /etc/csh.login -p wa -k system-config
-w /etc/crontab -p wa -k system-config
-w /etc/at.allow -p wa -k system-config
-w /etc/at.deny -p wa -k system-config
-w /etc/cron.allow -p wa -k system-config
-w /etc/cron.deny -p wa -k system-config
-w /etc/cron.d/ -p wa -k system-config
-w /etc/cron.hourly/ -p wa -k system-config
-w /etc/cron.daily/ -p wa -k system-config
-w /etc/cron.weekly/ -p wa -k system-config
-w /etc/cron.monthly/ -p wa -k system-config
-w /etc/anacrontab -p wa -k system-config
-w /var/spool/cron/crontabs/ -p wa -k system-config
-w /etc/sysctl.conf -p wa -k system-config
-w /etc/modprobe.d/ -p wa -k system-config
-w /etc/apt/sources.list -p wa -k system-config
-w /etc/apt/sources.list.d/ -p wa -k system-config
-w /etc/resolv.conf -p wa -k system-config
-w /etc/hosts -p wa -k system-config
-w /etc/network/interfaces -p wa -k system-config
-w /etc/fstab -p wa -k system-config

# Audit module loading and unloading
# ATT&CK: T1547.006 (Boot or Logon Autostart: Kernel Modules and Extensions)
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules
-a always,exit -F arch=b32 -S init_module -S delete_module -k modules
EOF

# Secure the audit rules file permissions
chmod 600 "$audit_rules_file"
chown root:root "$audit_rules_file"

# Reload auditd rules
augenrules --load 2>/dev/null || service auditd restart
